
server:
  port: 8081

spring:
  application:
    name: project-service
  datasource:
    url: jdbc:mysql://localhost:3308/project_db?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    table: flyway_schema_history
    enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


